---
kind: pipeline
type: docker
name: default

common_envs: &common_envs
    MYACCESSKEYID:
        from_secret: MYACCESSKEYID
    MYSECRETACCESSKEY:
        from_secret: MYSECRETACCESSKEY

steps:
- name: deploy-beta
  image: node
  commands:
  - npm install
  - npm run test
  - npm run deploy
  environment:
      << : *common_envs
      BUCKET: assets-autodeploy
      ENVIRONMENT: beta
  when:
    branch:
      - beta

steps:
- name: deploy-prod
  image: node
  commands:
  - npm install
  - npm run test
  - npm run deploy
  environment:
      << : *common_envs
      BUCKET: assets-autodeploy
      ENVIRONMENT: prod
  when:
    branch:
      - master

trigger:
  branch:
  - master
  - beta
