---
kind: pipeline
type: docker
name: default

common_envs: &common_envs
    ACCESSKEYID:
        from_secret: ACCESSKEYID
    SECRETACCESSKEY:
        from_secret: SECRETACCESSKEY

steps:
- name: deploybeta
  image: node
  commands:
  - npm install
  - npm run test
##  - npm run deploy
  environment:
      << : *common_envs
      BUCKET: assets-autodeploy
      ENVIRONMENT: beta
  when:
    branch:
      - beta

steps:
- name: deployprod
  image: node
  commands:
  - npm install
  - npm run test
  - npm run deploy
  environment:
      << : *common_envs
      BUCKET: assets-autodeploy
      ENVIRONMENT: prod
  when:
    branch:
      - master

trigger:
  branch:
  - master
  - beta
